server:
  port: 8083
spring:
  application:
    name: medical-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/csi_medical}
    username: ${SPRING_DATASOURCE_USERNAME:csi_medical}
    password: ${SPRING_DATASOURCE_PASSWORD:csi_medical}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
security:
  jwt:
    secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-256-bit-secret}
clients:
  profile-service-url: ${PROFILE_SERVICE_URL:http://localhost:8082}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health,info
