server:
  port: 8082
spring:
  application:
    name: profile-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/csi_profile}
    username: ${SPRING_DATASOURCE_USERNAME:csi_profile}
    password: ${SPRING_DATASOURCE_PASSWORD:csi_profile}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
security:
  jwt:
    secret: ${JWT_SECRET:change-me-change-me-change-me-change-me-256-bit-secret}
  sensitive-data-key: ${SENSITIVE_DATA_KEY:change-me-sensitive-data-key-for-development}
internal:
  auth-service-secret: ${INTERNAL_SERVICE_SECRET:dev-internal-secret}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health,info
